### ISSUE TITLE
mopline create_cov error

### ISSUE THREAD

**Issue by jingydz** [stat-lab/MOPline#10]
Hi, thank you for developing this wonderful pipeline.

When I run the mopline create_cov module, I have a question.
command: mopline create_cov -b sample.bam -r hg38.fasta -rl 150 -n 2

on the terminal, I got:
command: create_cov Args: -b sample.bam -r hg38.fasta -rl 150 -n 2
mopline create_cov: /xxx/software/MOPline/scripts/create_coverage_file_bam.pl -b sample.bam -r hg38.fasta -rl 150 -n 2
sample: chr1 finished:
sample: chr2 finished:
sample: chr3 finished:
sample: chr4 finished:
sample: chr5 finished:
sample: chr6 finished:
sample: chr7 finished:
sample: chr8 finished:
sample: chr9 finished:
sample: chr10 finished:
sample: chr11 finished:
sample: chr12 finished:
sample: chr13 finished:
sample: chr14 finished:
sample: chr15 finished:
sample: chr16 finished:
sample: chr17 finished:
sample: chr18 finished:
sample: chr19 finished:
sample: chr20 finished:
sample: chr21 finished:
sample: chr22 finished:
sample: chrX finished:
sample: chrY finished:
Coverage calculation completed:

then I got nothing, and this command was finished. 

Do you know why?

thanks in advance.

**Comment by stat-lab** [comment]
Do you find Cov directories in each sample directory? If Cov directories have no files, show the content of a command.log file (which may be .command.log if -p option has not been specified).

**Comment by jingydz** [comment]
Thank you very much!!
when I used the "sample.cov.input", I got the Cov directories.

$ cat sample.cov.input
/path/sample   sample.bam

mopline create_cov -b sample.cov.input -r hg38.fasta -rl 150 -n 4

$ ls sample/Cov/
sample.chr10.cov.gz  sample.chr12.cov.gz  sample.chr14.cov.gz  sample.chr16.cov.gz  sample.chr18.cov.gz  sample.chr1.cov.gz   sample.chr21.cov.gz  sample.chr2.cov.gz  sample.chr4.cov.gz  sample.chr6.cov.gz  sample.chr8.cov.gz  sample.chrX.cov.gz
sample.chr11.cov.gz  sample.chr13.cov.gz  sample.chr15.cov.gz  sample.chr17.cov.gz  sample.chr19.cov.gz  sample.chr20.cov.gz  sample.chr22.cov.gz  sample.chr3.cov.gz  sample.chr5.cov.gz  sample.chr7.cov.gz  sample.chr9.cov.gz  sample.chrY.cov.gz
