### ISSUE TITLE
supplementing missing calls(SMC) step

### ISSUE THREAD

**Issue by jingydz** [stat-lab/MOPline#12]
Hi, when I running the smc step, I find there are some warnings in the 'smc_out.vcftool.log' file.

$ grep "arning" smc_out.vcftool.log
Warning: Input is unsorted, results may not be complete.
Warning: Input is unsorted, results may not be complete.
Warning: Input is unsorted, results may not be complete.
Warning: Input is unsorted, results may not be complete.
Warning: Input is unsorted, results may not be complete.
...

The error message indicates that my joint/jointcall.All-samples.vcf file is not sorted, but upon inspection, the file appears to be sorted. I also used the vcf-sort software to sort the file again, resulting in the joint/jointcall.All-samples.sort.vcf file, which is identical to the original. However, when running the command mopline smc -v joint/jointcall.All-samples.sort.vcf -ts 7tools -od smc -p smc_out --build 38 -n 6, I still receive these warnings. Why is this happening?

**Comment by jingydz** [comment]
I understand that during the filtering step, some structural variation (SV) sites are removed (approximately 3,000), but why do I find that a small number of SV sites (about 1,000) are also deleted after running smc?

**Comment by jingydz** [comment]
joint/jointcall.All-samples.sort.vcf
chr1    1565631 .       .       <DUP>   .       PASS    SVTYPE=DUP;SVLEN=97;END=1565727;SC=233;AF=0.2126;AC=233;AN=1096;DPR=1.56;SR=0.37        GT:GQ:VP:VL:DR:DS:SR    ./.:0:1565630:97:1.35:0:0.39    0/0:0:0:0:0:0:0

smc/smc_out.vcf
chr1    1565631 .       .       <DUP>   .       PASS    SVTYPE=DUP;SVLEN=97;END=1565727;SC=503;AF=0.6387;AC=700;AN=1096;DPR=1.39;SR=0.38;DPS=0.14       GT:GQ:VP:VL:DR:DS:SR:MC 1/1:39:1565630:97:1.35:0:0.39:0 1/1:0:1565631:97:1.25:0.5:0.36:3

I am also puzzled about the process of smc. For the ./. type, I can understand why genotypes exist, but why does 0/0 also become 1/1? Or why does 0/0 become 0/1?

**Comment by stat-lab** [comment]
In the joint call step, the SV genotype information is derived from the selected confident genotypes of SV/genotype calling tools used in the initial SV detection step. So, the genotypes of many SVs are undefined as './.'. In the SMC step, all SV genotypes are evaluated using the information for DPR, DR, DS, and previously defined genotypes. So, '0/0' and './.' genotypes defined in the joint call step could be '0/1' or '1/1' in the SMC step. SV sites with '0/0' genotype for all samples or with unbalanced 5'- and 3'-split ends for > 50% samples are deleted in the SMC step.

**Comment by jingydz** [comment]
Hi, w
hen I run smc to recover missing values, I always run out of memory (the running node has 2TB of memory). Can I split the samples or chromosomes in some way?

mopline smc -v joint/jointcall.All-samples.sort.vcf -ts 7tools -od smc -p smc_out --build 38 -n 20

29G Mar  8 17:41 jointcall.All-samples.sort.vcf


command: smc Args: -v joint/jointcall.All-samples.sort.vcf -ts 7tools -od smc -p smc_out --build 38 -n 20
mopline smc: /xxx/software/MOPline/scripts/genotype_SV_SMC_7.4.pl -v joint/jointcall.All-samples.sort.vcf -ts 7tools -od smc -p smc_out --build 38 -n 20
Total sample: 8431
#Total length of repeats:       295768357
1st step completed:
17: Sample re-searching completed:
...
2nd step completed:
Missing calls (MC): 1851419577  MC recovered from the original SV calls: 26847495
3rd step completed:
Out of memory!

May I ask why this is happening?

**Comment by jingydz** [comment]
Hi, w
hen I run smc to recover missing values, I always run out of memory (the running node has 2TB of memory). Can I split the samples or chromosomes in some way?

mopline smc -v joint/jointcall.All-samples.sort.vcf -ts 7tools -od smc -p smc_out --build 38 -n 20

29G Mar  8 17:41 jointcall.All-samples.sort.vcf


command: smc Args: -v joint/jointcall.All-samples.sort.vcf -ts 7tools -od smc -p smc_out --build 38 -n 20
mopline smc: /xxx/software/MOPline/scripts/genotype_SV_SMC_7.4.pl -v joint/jointcall.All-samples.sort.vcf -ts 7tools -od smc -p smc_out --build 38 -n 20
Total sample: 8431
#Total length of repeats:       295768357
1st step completed:
17: Sample re-searching completed:
...
2nd step completed:
Missing calls (MC): 1851419577  MC recovered from the original SV calls: 26847495
3rd step completed:
Out of memory!

May I ask why this is happening?

**Comment by stat-lab** [comment]
Your input vcf file in the SMC step seems very large. So, you should conduct the SMC step for each chromosome by specifying the -c option. It would be better to run the jobs for each cromosome in batch or with a job management system.

**Comment by jingydz** [comment]
##fileformat=VCFv4.0
##fileDate=20240202
##source=MOPline-1.7
##reference=hs38
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variation (SV)">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles (0 when undefined)">
##INFO=<ID=DPS,Number=1,Type=Float,Description="Mean ratio of 50-bp-window-fractions with inconsistent DPR">
##INFO=<ID=SVANN,Number=1,Type=String,Description="Affected_Gene,GeneID|GeneName|Region">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=DUP,Description="Duplication">
##ALT=<ID=INS,Description="Insertion of undefined sequence">
##ALT=<ID=INV:Description="Inversion">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype quality">
##FORMAT=<ID=VP,Number=1,Type=Integer,Description="Position of SV for a sample">
##FORMAT=<ID=VL,Number=1,Type=Integer,Description="Length of SV for a sample">
##FORMAT=<ID=DR,Number=1,Type=Float,Description="Ratio of read depth in CNV region to that in its flanking regions for a sample">
##FORMAT=<ID=DS,Number=1,Type=Float,Description="Ratio of inconsistent DR segments (> 0.8 for DEL, < 1.1 for DUP) in DEL and DUP">
##FORMAT=<ID=SR,Number=1,Type=Float,Description="Ratio of breakpoints of soft-clipped reads in the read depth at the 50- or 100-bp window">
##FORMAT=<ID=MC,Number=1,Type=Integer,Description="Levels of SMC genotyping">
##FORMAT=<ID=AN,Number=1,Type=String,Description="Annotation for each sample, E:exon, AE:all exons, I:intron, 5U:5UTR, 3U:3UTR, 5F:flank5, 3F:flank3">
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr2,length=242193529>
##contig=<ID=chr3,length=198295559>
##contig=<ID=chr4,length=190214555>
##contig=<ID=chr5,length=181538259>
##contig=<ID=chr6,length=170805979>
##contig=<ID=chr7,length=159345973>
##contig=<ID=chr8,length=145138636>
##contig=<ID=chr9,length=138394717>
##contig=<ID=chr10,length=133797422>
##contig=<ID=chr11,length=135086622>
##contig=<ID=chr12,length=133275309>
##contig=<ID=chr13,length=114364328>
##contig=<ID=chr14,length=107043718>
##contig=<ID=chr15,length=101991189>
##contig=<ID=chr16,length=90338345>
##contig=<ID=chr17,length=83257441>
##contig=<ID=chr18,length=80373285>
##contig=<ID=chr19,length=58617616>
##contig=<ID=chr20,length=64444167>
##contig=<ID=chr21,length=46709983>
##contig=<ID=chr22,length=50818468>
##contig=<ID=chrX,length=156040895>
##contig=<ID=chrY,length=57227415>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT


The content above is the header from the file smc/annotate.AS.annot.filter.vcf that I obtained after running mopline. I would like to ask why the header does not include information for 'END', 'SC', 'AF', 'DPR', 'SR', etc., which is causing me to be unable to process it with VCF processing software. Can I add such parameters to the header myself? for example:

##INFO=<ID=END,Number=1,Type=String,Description="End position of the structural variant">
##INFO=<ID=SC,Number=.,Type=String,Description="Sample call confidence">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##INFO=<ID=DPR,Number=.,Type=Float,Description="Depth of reads from the reference allele">
##INFO=<ID=SR,Number=.,Type=Float,Description="Supporting reads from the reference allele">

**Comment by stat-lab** [comment]
Sorry for your trouble. A bug in the merge_SV_calls_ALLtype.pl script was fixed. This ploblem can be avoided using the updated scripts, but runs from step-1 or SMC-step are required. So, you may add the following header lines to the header of your final vcf file.

##INFO=<ID=END,Number=1,Type=Integer,Description="End position of SV">
##INFO=<ID=AF,Number=1,Type=Float,Description="Allele frequency">
##INFO=<ID=AC,Number=1,Type=Integer,Description="Allele count">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Allele number">
##INFO=<ID=SC,Number=1,Type=Integer,Description="Number of samples carrying the SV allele">
##INFO=<ID=DPR,Number=1,Type=Float,Description="Mean ratio of read depth in CNV region to that in its flanking regions">
##INFO=<ID=SR,Number=1,Type=Float,Description="Mean ratio of breakpoints from soft-clipped reads in the read depth at the window">
##INFO=<ID=DPS,Number=1,Type=Float,Description="Mean ratio of 50-bp-window-fractions with inconsistent DPR">
