### ISSUE TITLE
Bug in run_MELT.pl 

### ISSUE THREAD

**Issue by akiss-me** [stat-lab/MOPline#6]
Hi, I found a minor bug in run_MELT.pl 

Without specifying the -mt option ("ALU,LINE1,SVA,HERVK"), the program exits and generates a VCF with size 0.

**Comment by stat-lab** [comment]
Thank you for pointing out the bug in MELT run script. I fixed the bug in run_SVcallers/run_MELT.pl, which was the default MELT target strings for human, specified with -mt option. I also updated the v1.8.2 release tar.gz file and the singularity file, mopline.sif, at http://jenger.riken.jp/en/data.

**Comment by akiss-me** [comment]
Thanks!
